--1
SELECT *
FROM JOB;

--2
SELECT JOB_NAME
FROM JOB;

--3
SELECT *
FROM DEPARTMENT;

--4
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEE;

--5
SELECT HIRE_DATE, EMP_NAME, SALARY
FROM EMPLOYEE;

--6
SELECT EMP_NAME, SALARY * 12 AS"연봉",
(SALARY + (SALARY * NVL(BONUS,0))) * 12 AS"총수령액",
(((SALARY + (SALARY * NVL(BONUS,0))) * 12) - (SALARY * 12 * 0.03)) AS"실수령액"
FROM EMPLOYEE;

--7
SELECT EMP_NAME, SALARY, HIRE_DATE, PHONE
FROM EMPLOYEE 
JOIN SAL_GRADE ON (SALARY BETWEEN MIN_SAL AND MAX_SAL)
WHERE SAL_LEVEL = 'S1';

--8
SELECT EMP_NAME, SALARY,
((SALARY + (SALARY * BONUS)) * 12) * 0.97 AS"실수령액", HIRE_DATE
FROM EMPLOYEE
WHERE(((SALARY + (SALARY * NVL(BONUS,0))) * 12) - (SALARY * 12 * 0.03)) >= 50000000;

--9
SELECT *
FROM EMPLOYEE
WHERE SALARY > 4000000 AND JOB_CODE = 'J2';

--10
SELECT EMP_NAME, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE = 'D9' OR DEPT_CODE = 'D5')
AND HIRE_DATE < '2002/01/01';

--11
SELECT *
FROM EMPLOYEE
WHERE HIRE_DATE >= '90/01/01'
AND HIRE_DATE <= '01/01/01';

--12
SELECT EMP_NAME
FROM EMPLOYEE
WHERE SUBSTR(EMP_NAME,3,1) = '연';

--13
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE PHONE NOT LIKE '010%';

--14
SELECT *
FROM EMPLOYEE
WHERE EMAIL LIKE '____\_%' ESCAPE '\'
AND (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6')
AND HIRE_DATE BETWEEN '90/01/01' AND '00/12/01'
AND SALARY >= 2700000;

--15.
SELECT EMP_NAME "사원명",
SUBSTR(EMP_NO, 1, 2) "생년",
SUBSTR(EMP_NO, 3, 2) "생월",
SUBSTR(EMP_NO, 5, 2) "생일"
FROM EMPLOYEE;

--16
--SELECT EMP_NAMA, SUBSTR(EMP_NO, 1, 7) || '-*******'
SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO, 1, 7), 14, '*')
FROM EMPLOYEE;

--17
SELECT EMP_NAME,
FLOOR(ABS(HIRE_DATE - SYSDATE)) AS "근무일수1",
FLOOR(ABS(SYSDATE - HIRE_DATE)) AS "근무일수2"
FROM EMPLOYEE;

--18
SELECT *
FROM EMPLOYEE
WHERE MOD (EMP_ID, 2) = 1;

--19
SELECT *
FROM EMPLOYEE
--WHERE MONTHS_BETWEEN(SYSDATE, HIRE_DATE) > 240;
WHERE ADD_MONTHS(HIRE_DATE, 240) < SYSDATE;

--20
SELECT EMP_NAME, TO_CHAR(SALARY, 'L999,999,999')
FROM EMPLOYEE;

--21
SELECT EMP_NAME, DEPT_CODE,
SUBSTR(EMP_NO, 1, 2) || '년' || SUBSTR(EMP_NO, 3, 2) || '월' || SUBSTR(EMP_NO, 5, 2) || '일' AS "생일",
EXTRACT(YEAR FROM SYSDATE) -
EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO, 1, 2), 'RRRR'))
FROM EMPLOYEE;

--22
SELECT EMP_ID, EMP_NAME, DEPT_CODE,
CASE
WHEN DEPT_CODE = 'D5' THEN '총무부'
WHEN DEPT_CODE = 'D6' THEN '기획부'
WHEN DEPT_CODE = 'D9' THEN '영업부'
END
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5', 'D6', 'D9')
ORDER BY DEPT_CODE;

--23
SELECT EMP_NAME,
SUBSTR(EMP_NO, 1, 6) AS "앞자리",
SUBSTR(EMP_NO, 8) AS "뒷자리",
TO_NUMBER(SUBSTR(EMP_NO, 1, 6) + SUBSTR(EMP_NO, 8))
FROM EMPLOYEE
WHERE EMP_ID = 201;

--24
SELECT SUM((SALARY + (SALARY * NVL(BONUS, 0))) * 12)
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5';

--25
SELECT COUNT(*),
COUNT(DECODE(TO_CHAR(EXTRACT(YEAR FROM HIRE_DATE)), '2001', 1)) AS "2001년",
COUNT(DECODE(TO_CHAR(EXTRACT(YEAR FROM HIRE_DATE)), '2002', 1)) AS "2002년",
COUNT(DECODE(TO_CHAR(EXTRACT(YEAR FROM HIRE_DATE)), '2003', 1)) AS "2003년",
COUNT(DECODE(TO_CHAR(EXTRACT(YEAR FROM HIRE_DATE)), '2004', 1)) AS "2004년"
FROM EMPLOYEE;