CREATE TABLE STUDENT(
    SNAME VARCHAR2(20) NOT NULL,
    SUBJECT VARCHAR2(20) NOT NULL,
    SCORE NUMBER PRIMARY KEY
);
DROP TABLE MEMBER2;



CREATE TABLE MEMBER2(
    MEM_NO NUMBER PRIMARY KEY,
    ID VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    GENDER CHAR(1) CHECK(GENDER IN ('M', 'F')),
    AGE NUMBER
);



CREATE SEQUENCE SEQ_MEM_NO
NOCACHE;

INSERT INTO MEMBER2
VALUES(SEQ_MEM_NO.NEXTVAL, 'MEMBER01', 'Áø¿µÀç','PASS01', 'jjaman3@naver.com', 'M', 30);

DROP SEQUENCE SEQ_MEM_NO;

COMMIT;


